/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.andrew.bookscanner;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int webview=0x7f030000;
    }
    public static final class string {
        public static final int helloText=0x7f040002;
        public static final int myApplicationName=0x7f040000;
        public static final int scanner=0x7f040001;
    }
}
